site_name: ASR Crash database <img src="https://cdn.img.wenhairu.com/images/2020/10/11/CkiRP.png">
site_favicon: ASR.ico
nav:
- Tools: 
    - cmd: cmd-usage.md
    - FFmpeg: FFmpeg-usage.md
    - Git: Git-usage.md
    - HTML: html-usage.md
    - Markdown: Markdown-usage.md
    - MkDocs: MkDocs-usage.md
    - PowerToys: PowerToys.md
    - Selenium: Selenium-usage.md
    - you-get: you-get-usage.md

- Configuration:
    - Cmder: Cmder-configuration.md
    - pip3: pip3-configuration.md
    - SSH: SSH-configuration.md
    - WSL: WSL-configuration.md

- Textbook:
    - Reference for Engineering: Reference-for-Engineering.md

theme: readthedocs
copyright: Copyright© 2020 ASR-Crash