site_name: Crash database 
<img src="https://github.com/ASR-Crash/Crash-database/blob/master/docs/ASR-Round.png/")
site_favicon: ASR.ico
nav:
- Tools: 
    - Git: Git-usage.md
    - you-get: you-get-usage.md
    - FFmpeg: FFmpeg-usage.md
    - Selenium: Selenium-usage.md
    - MkDocs: MkDocs-usage.md
- Configuration:
    - pip3: pip3-configuration.md
    - WSL: WSL-configuration.md
    - Cmder: Cmder-configuration.md
theme: readthedocs
copyright: Copyright© 2020 ASR-Crash