site_name: ASR-Crash Shared Database
site_favicon: ASR.ico
nav:
- Tools: 
    - cmd: cmd-usage.md
    - FFmpeg: FFmpeg-usage.md
    - Git: Git-usage.md
    - HTML: html-usage.md
    - InteractiveHtmlBom: InteractiveHtmlBom-usage.md
    - Markdown: Markdown-usage.md
    - MkDocs: MkDocs-usage.md
    - OpenOCD: OpenOCD-usage.md
    - PowerToys: PowerToys-usage.md
    - Selenium: Selenium-usage.md
    - XMind: XMind-usage.md
    - you-get: you-get-usage.md

- Configuration:
    - Cmder: Cmder-configuration.md
    - iPad to PC: iPad-to-PC-configuration.md   
    - pip3: pip3-configuration.md
    - RaspberryPi: RaspberryPi-configuration.md
    - SSH: SSH-configuration.md
    - Typora to bilibili: Typora-to-bilibili-configuration.md
    - WSL: WSL-configuration.md

- Textbook:
    - Link for FOSS: Link-for-FOSS.md
    - Reference for Engineering: Reference-for-Engineering.md

theme: cyborg
copyright: Copyright© 2023 Crash, Alliance of Science Research. <img src='https://asr-crash.github.io/Crash-database/logo/ASR-WS.png' width='64'> |&nbsp; <img src='https://asr-crash.github.io/Crash-database/logo/Crash-WS.png' width='160'> 