site_name: ASR Crash database <img src="https://cdn.img.wenhairu.com/images/2020/10/11/CkiRP.png">
site_favicon: ASR.ico
nav:
- Tools: 
    - Git: Git-usage.md
    - you-get: you-get-usage.md
    - FFmpeg: FFmpeg-usage.md
    - Selenium: Selenium-usage.md
    - MkDocs: MkDocs-usage.md
    - cmd: cmd-usage.md
- Configuration:
    - pip3: pip3-configuration.md
    - WSL: WSL-configuration.md
    - Cmder: Cmder-configuration.md
theme: readthedocs
copyright: Copyright© 2020 ASR-Crash